#Site
title: Erin Price
description: This is Erin's home.
logo: favicon.png
url: erinpricewrites.github.io
rss_url: /feed.xml

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Comment
comment:
  # disqus:     
  # duoshuo: kongsong
  # youyan: 2122392
  # laibili: MTAyMC8yODgzNC81NDA0

# Website analytics
# google_analytics: UA-82494501-1
# baidu_analytics: 5b31ffbbdc6cff18727f3adf75a03777    #from //hm.baidu.com/hm.js?***

# Author information:
author:
  #resume: /resume
  name: Erin Price     #the name of Blog section
  about_me: Erin Price writes children's, middle grade, and young adult fiction. Her young adult novel, <i>Walls</i>, is available on Amazon, and she is currently working on a new middle grade novel, <i>Lucky Me</i>, about a pair of quirky sisters.  Her stories and articles have been published in magazines such as the <i>Friend</i> and <i>LDS Living</i>.
 
# Social Links
email:               erinpricewrites@gmail.com
#google.plus:        username
#twitter:            username
# facebook:            kongsong
github:              erinpricewrites
# stackoverflow:      6438519/song-kong   #from a "http://stackoverflow.com/users/123456/username" link
# linkedin:           kongsong
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile,.sass-cache,.DS_Store,.idea]
